/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "auth.proto" (package "svyne.auth", syntax proto3)
// tslint:disable
import { Empty } from "./common";
import { AckResponse } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message svyne.auth.LoginRequest
 */
export interface LoginRequest {
    /**
     * @generated from protobuf field: string email = 1;
     */
    email: string;
    /**
     * @generated from protobuf field: string password = 2;
     */
    password: string;
    /**
     * @generated from protobuf field: string tenant_slug = 3;
     */
    tenantSlug: string;
}
/**
 * @generated from protobuf message svyne.auth.GoogleSignInRequest
 */
export interface GoogleSignInRequest {
    /**
     * @generated from protobuf field: string google_token = 1;
     */
    googleToken: string;
    /**
     * @generated from protobuf field: string tenant_slug = 2;
     */
    tenantSlug: string;
}
/**
 * @generated from protobuf message svyne.auth.RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * @generated from protobuf field: string refresh_token = 1;
     */
    refreshToken: string;
}
/**
 * @generated from protobuf message svyne.auth.LogoutRequest
 */
export interface LogoutRequest {
    /**
     * @generated from protobuf field: string session_hash = 1;
     */
    sessionHash: string;
}
/**
 * @generated from protobuf message svyne.auth.MagicLinkRequest
 */
export interface MagicLinkRequest {
    /**
     * @generated from protobuf field: string email = 1;
     */
    email: string;
    /**
     * @generated from protobuf field: string tenant_slug = 2;
     */
    tenantSlug: string;
}
/**
 * @generated from protobuf message svyne.auth.MagicLinkVerifyRequest
 */
export interface MagicLinkVerifyRequest {
    /**
     * @generated from protobuf field: string token = 1;
     */
    token: string;
}
/**
 * @generated from protobuf message svyne.auth.PasswordResetRequest
 */
export interface PasswordResetRequest {
    /**
     * @generated from protobuf field: string email = 1;
     */
    email: string;
    /**
     * @generated from protobuf field: string tenant_slug = 2;
     */
    tenantSlug: string;
}
/**
 * @generated from protobuf message svyne.auth.SetPasswordRequest
 */
export interface SetPasswordRequest {
    /**
     * @generated from protobuf field: string token = 1;
     */
    token: string;
    /**
     * @generated from protobuf field: string new_password = 2;
     */
    newPassword: string;
}
/**
 * @generated from protobuf message svyne.auth.AuthResponse
 */
export interface AuthResponse {
    /**
     * @generated from protobuf field: string access_token = 1;
     */
    accessToken: string;
    /**
     * @generated from protobuf field: string refresh_token = 2;
     */
    refreshToken: string;
    /**
     * @generated from protobuf field: int64 expires_at = 3;
     */
    expiresAt: string;
    /**
     * @generated from protobuf field: svyne.auth.UserProfile user = 4;
     */
    user?: UserProfile;
}
/**
 * @generated from protobuf message svyne.auth.UserProfile
 */
export interface UserProfile {
    /**
     * @generated from protobuf field: string users_id = 1;
     */
    usersId: string;
    /**
     * @generated from protobuf field: string tenants_id = 2;
     */
    tenantsId: string;
    /**
     * @generated from protobuf field: string email = 3;
     */
    email: string;
    /**
     * @generated from protobuf field: string first_name = 4;
     */
    firstName: string;
    /**
     * @generated from protobuf field: string last_name = 5;
     */
    lastName: string;
    /**
     * @generated from protobuf field: int32 role = 6;
     */
    role: number;
    /**
     * @generated from protobuf field: string tenant_slug = 7;
     */
    tenantSlug: string;
    /**
     * @generated from protobuf field: bool email_verified = 8;
     */
    emailVerified: boolean;
    /**
     * @generated from protobuf field: string avatar_url = 9;
     */
    avatarUrl: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class LoginRequest$Type extends MessageType<LoginRequest> {
    constructor() {
        super("svyne.auth.LoginRequest", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "tenant_slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LoginRequest>): LoginRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.email = "";
        message.password = "";
        message.tenantSlug = "";
        if (value !== undefined)
            reflectionMergePartial<LoginRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LoginRequest): LoginRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string email */ 1:
                    message.email = reader.string();
                    break;
                case /* string password */ 2:
                    message.password = reader.string();
                    break;
                case /* string tenant_slug */ 3:
                    message.tenantSlug = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LoginRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string email = 1; */
        if (message.email !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.email);
        /* string password = 2; */
        if (message.password !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.password);
        /* string tenant_slug = 3; */
        if (message.tenantSlug !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.tenantSlug);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.LoginRequest
 */
export const LoginRequest = new LoginRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GoogleSignInRequest$Type extends MessageType<GoogleSignInRequest> {
    constructor() {
        super("svyne.auth.GoogleSignInRequest", [
            { no: 1, name: "google_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tenant_slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GoogleSignInRequest>): GoogleSignInRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.googleToken = "";
        message.tenantSlug = "";
        if (value !== undefined)
            reflectionMergePartial<GoogleSignInRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GoogleSignInRequest): GoogleSignInRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string google_token */ 1:
                    message.googleToken = reader.string();
                    break;
                case /* string tenant_slug */ 2:
                    message.tenantSlug = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GoogleSignInRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string google_token = 1; */
        if (message.googleToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.googleToken);
        /* string tenant_slug = 2; */
        if (message.tenantSlug !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tenantSlug);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.GoogleSignInRequest
 */
export const GoogleSignInRequest = new GoogleSignInRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefreshTokenRequest$Type extends MessageType<RefreshTokenRequest> {
    constructor() {
        super("svyne.auth.RefreshTokenRequest", [
            { no: 1, name: "refresh_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RefreshTokenRequest>): RefreshTokenRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.refreshToken = "";
        if (value !== undefined)
            reflectionMergePartial<RefreshTokenRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RefreshTokenRequest): RefreshTokenRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string refresh_token */ 1:
                    message.refreshToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RefreshTokenRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string refresh_token = 1; */
        if (message.refreshToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.refreshToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.RefreshTokenRequest
 */
export const RefreshTokenRequest = new RefreshTokenRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogoutRequest$Type extends MessageType<LogoutRequest> {
    constructor() {
        super("svyne.auth.LogoutRequest", [
            { no: 1, name: "session_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LogoutRequest>): LogoutRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessionHash = "";
        if (value !== undefined)
            reflectionMergePartial<LogoutRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LogoutRequest): LogoutRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string session_hash */ 1:
                    message.sessionHash = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LogoutRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string session_hash = 1; */
        if (message.sessionHash !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sessionHash);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.LogoutRequest
 */
export const LogoutRequest = new LogoutRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MagicLinkRequest$Type extends MessageType<MagicLinkRequest> {
    constructor() {
        super("svyne.auth.MagicLinkRequest", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tenant_slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MagicLinkRequest>): MagicLinkRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.email = "";
        message.tenantSlug = "";
        if (value !== undefined)
            reflectionMergePartial<MagicLinkRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MagicLinkRequest): MagicLinkRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string email */ 1:
                    message.email = reader.string();
                    break;
                case /* string tenant_slug */ 2:
                    message.tenantSlug = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MagicLinkRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string email = 1; */
        if (message.email !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.email);
        /* string tenant_slug = 2; */
        if (message.tenantSlug !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tenantSlug);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.MagicLinkRequest
 */
export const MagicLinkRequest = new MagicLinkRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MagicLinkVerifyRequest$Type extends MessageType<MagicLinkVerifyRequest> {
    constructor() {
        super("svyne.auth.MagicLinkVerifyRequest", [
            { no: 1, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MagicLinkVerifyRequest>): MagicLinkVerifyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.token = "";
        if (value !== undefined)
            reflectionMergePartial<MagicLinkVerifyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MagicLinkVerifyRequest): MagicLinkVerifyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string token */ 1:
                    message.token = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MagicLinkVerifyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string token = 1; */
        if (message.token !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.token);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.MagicLinkVerifyRequest
 */
export const MagicLinkVerifyRequest = new MagicLinkVerifyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PasswordResetRequest$Type extends MessageType<PasswordResetRequest> {
    constructor() {
        super("svyne.auth.PasswordResetRequest", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tenant_slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PasswordResetRequest>): PasswordResetRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.email = "";
        message.tenantSlug = "";
        if (value !== undefined)
            reflectionMergePartial<PasswordResetRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PasswordResetRequest): PasswordResetRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string email */ 1:
                    message.email = reader.string();
                    break;
                case /* string tenant_slug */ 2:
                    message.tenantSlug = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PasswordResetRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string email = 1; */
        if (message.email !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.email);
        /* string tenant_slug = 2; */
        if (message.tenantSlug !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tenantSlug);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.PasswordResetRequest
 */
export const PasswordResetRequest = new PasswordResetRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetPasswordRequest$Type extends MessageType<SetPasswordRequest> {
    constructor() {
        super("svyne.auth.SetPasswordRequest", [
            { no: 1, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "new_password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SetPasswordRequest>): SetPasswordRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.token = "";
        message.newPassword = "";
        if (value !== undefined)
            reflectionMergePartial<SetPasswordRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetPasswordRequest): SetPasswordRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string token */ 1:
                    message.token = reader.string();
                    break;
                case /* string new_password */ 2:
                    message.newPassword = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetPasswordRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string token = 1; */
        if (message.token !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.token);
        /* string new_password = 2; */
        if (message.newPassword !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.newPassword);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.SetPasswordRequest
 */
export const SetPasswordRequest = new SetPasswordRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AuthResponse$Type extends MessageType<AuthResponse> {
    constructor() {
        super("svyne.auth.AuthResponse", [
            { no: 1, name: "access_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "refresh_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "expires_at", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 4, name: "user", kind: "message", T: () => UserProfile }
        ]);
    }
    create(value?: PartialMessage<AuthResponse>): AuthResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accessToken = "";
        message.refreshToken = "";
        message.expiresAt = "0";
        if (value !== undefined)
            reflectionMergePartial<AuthResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AuthResponse): AuthResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string access_token */ 1:
                    message.accessToken = reader.string();
                    break;
                case /* string refresh_token */ 2:
                    message.refreshToken = reader.string();
                    break;
                case /* int64 expires_at */ 3:
                    message.expiresAt = reader.int64().toString();
                    break;
                case /* svyne.auth.UserProfile user */ 4:
                    message.user = UserProfile.internalBinaryRead(reader, reader.uint32(), options, message.user);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AuthResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string access_token = 1; */
        if (message.accessToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.accessToken);
        /* string refresh_token = 2; */
        if (message.refreshToken !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.refreshToken);
        /* int64 expires_at = 3; */
        if (message.expiresAt !== "0")
            writer.tag(3, WireType.Varint).int64(message.expiresAt);
        /* svyne.auth.UserProfile user = 4; */
        if (message.user)
            UserProfile.internalBinaryWrite(message.user, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.AuthResponse
 */
export const AuthResponse = new AuthResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserProfile$Type extends MessageType<UserProfile> {
    constructor() {
        super("svyne.auth.UserProfile", [
            { no: 1, name: "users_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tenants_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "first_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "last_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "role", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "tenant_slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "email_verified", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "avatar_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UserProfile>): UserProfile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.usersId = "";
        message.tenantsId = "";
        message.email = "";
        message.firstName = "";
        message.lastName = "";
        message.role = 0;
        message.tenantSlug = "";
        message.emailVerified = false;
        message.avatarUrl = "";
        if (value !== undefined)
            reflectionMergePartial<UserProfile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserProfile): UserProfile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string users_id */ 1:
                    message.usersId = reader.string();
                    break;
                case /* string tenants_id */ 2:
                    message.tenantsId = reader.string();
                    break;
                case /* string email */ 3:
                    message.email = reader.string();
                    break;
                case /* string first_name */ 4:
                    message.firstName = reader.string();
                    break;
                case /* string last_name */ 5:
                    message.lastName = reader.string();
                    break;
                case /* int32 role */ 6:
                    message.role = reader.int32();
                    break;
                case /* string tenant_slug */ 7:
                    message.tenantSlug = reader.string();
                    break;
                case /* bool email_verified */ 8:
                    message.emailVerified = reader.bool();
                    break;
                case /* string avatar_url */ 9:
                    message.avatarUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserProfile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string users_id = 1; */
        if (message.usersId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.usersId);
        /* string tenants_id = 2; */
        if (message.tenantsId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tenantsId);
        /* string email = 3; */
        if (message.email !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.email);
        /* string first_name = 4; */
        if (message.firstName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.firstName);
        /* string last_name = 5; */
        if (message.lastName !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.lastName);
        /* int32 role = 6; */
        if (message.role !== 0)
            writer.tag(6, WireType.Varint).int32(message.role);
        /* string tenant_slug = 7; */
        if (message.tenantSlug !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.tenantSlug);
        /* bool email_verified = 8; */
        if (message.emailVerified !== false)
            writer.tag(8, WireType.Varint).bool(message.emailVerified);
        /* string avatar_url = 9; */
        if (message.avatarUrl !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.avatarUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.auth.UserProfile
 */
export const UserProfile = new UserProfile$Type();
/**
 * @generated ServiceType for protobuf service svyne.auth.AuthService
 */
export const AuthService = new ServiceType("svyne.auth.AuthService", [
    { name: "Login", options: {}, I: LoginRequest, O: AuthResponse },
    { name: "GoogleSignIn", options: {}, I: GoogleSignInRequest, O: AuthResponse },
    { name: "RefreshToken", options: {}, I: RefreshTokenRequest, O: AuthResponse },
    { name: "Logout", options: {}, I: LogoutRequest, O: AckResponse },
    { name: "RequestMagicLink", options: {}, I: MagicLinkRequest, O: AckResponse },
    { name: "VerifyMagicLink", options: {}, I: MagicLinkVerifyRequest, O: AuthResponse },
    { name: "RequestPasswordReset", options: {}, I: PasswordResetRequest, O: AckResponse },
    { name: "SetPassword", options: {}, I: SetPasswordRequest, O: AckResponse },
    { name: "Me", options: {}, I: Empty, O: UserProfile }
]);
