/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "auth.proto" (package "svyne.auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./auth";
import type { UserProfile } from "./auth";
import type { Empty } from "./common";
import type { SetPasswordRequest } from "./auth";
import type { PasswordResetRequest } from "./auth";
import type { MagicLinkVerifyRequest } from "./auth";
import type { MagicLinkRequest } from "./auth";
import type { AckResponse } from "./common";
import type { LogoutRequest } from "./auth";
import type { RefreshTokenRequest } from "./auth";
import type { GoogleSignInRequest } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AuthResponse } from "./auth";
import type { LoginRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service svyne.auth.AuthService
 */
export interface IAuthServiceClient {
    /**
     * @generated from protobuf rpc: Login(svyne.auth.LoginRequest) returns (svyne.auth.AuthResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: GoogleSignIn(svyne.auth.GoogleSignInRequest) returns (svyne.auth.AuthResponse);
     */
    googleSignIn(input: GoogleSignInRequest, options?: RpcOptions): UnaryCall<GoogleSignInRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: RefreshToken(svyne.auth.RefreshTokenRequest) returns (svyne.auth.AuthResponse);
     */
    refreshToken(input: RefreshTokenRequest, options?: RpcOptions): UnaryCall<RefreshTokenRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: Logout(svyne.auth.LogoutRequest) returns (svyne.common.AckResponse);
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: RequestMagicLink(svyne.auth.MagicLinkRequest) returns (svyne.common.AckResponse);
     */
    requestMagicLink(input: MagicLinkRequest, options?: RpcOptions): UnaryCall<MagicLinkRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: VerifyMagicLink(svyne.auth.MagicLinkVerifyRequest) returns (svyne.auth.AuthResponse);
     */
    verifyMagicLink(input: MagicLinkVerifyRequest, options?: RpcOptions): UnaryCall<MagicLinkVerifyRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: RequestPasswordReset(svyne.auth.PasswordResetRequest) returns (svyne.common.AckResponse);
     */
    requestPasswordReset(input: PasswordResetRequest, options?: RpcOptions): UnaryCall<PasswordResetRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: SetPassword(svyne.auth.SetPasswordRequest) returns (svyne.common.AckResponse);
     */
    setPassword(input: SetPasswordRequest, options?: RpcOptions): UnaryCall<SetPasswordRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: Me(svyne.common.Empty) returns (svyne.auth.UserProfile);
     */
    me(input: Empty, options?: RpcOptions): UnaryCall<Empty, UserProfile>;
}
/**
 * @generated from protobuf service svyne.auth.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Login(svyne.auth.LoginRequest) returns (svyne.auth.AuthResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, AuthResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GoogleSignIn(svyne.auth.GoogleSignInRequest) returns (svyne.auth.AuthResponse);
     */
    googleSignIn(input: GoogleSignInRequest, options?: RpcOptions): UnaryCall<GoogleSignInRequest, AuthResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GoogleSignInRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefreshToken(svyne.auth.RefreshTokenRequest) returns (svyne.auth.AuthResponse);
     */
    refreshToken(input: RefreshTokenRequest, options?: RpcOptions): UnaryCall<RefreshTokenRequest, AuthResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RefreshTokenRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Logout(svyne.auth.LogoutRequest) returns (svyne.common.AckResponse);
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, AckResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RequestMagicLink(svyne.auth.MagicLinkRequest) returns (svyne.common.AckResponse);
     */
    requestMagicLink(input: MagicLinkRequest, options?: RpcOptions): UnaryCall<MagicLinkRequest, AckResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<MagicLinkRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: VerifyMagicLink(svyne.auth.MagicLinkVerifyRequest) returns (svyne.auth.AuthResponse);
     */
    verifyMagicLink(input: MagicLinkVerifyRequest, options?: RpcOptions): UnaryCall<MagicLinkVerifyRequest, AuthResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<MagicLinkVerifyRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RequestPasswordReset(svyne.auth.PasswordResetRequest) returns (svyne.common.AckResponse);
     */
    requestPasswordReset(input: PasswordResetRequest, options?: RpcOptions): UnaryCall<PasswordResetRequest, AckResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<PasswordResetRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetPassword(svyne.auth.SetPasswordRequest) returns (svyne.common.AckResponse);
     */
    setPassword(input: SetPasswordRequest, options?: RpcOptions): UnaryCall<SetPasswordRequest, AckResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetPasswordRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Me(svyne.common.Empty) returns (svyne.auth.UserProfile);
     */
    me(input: Empty, options?: RpcOptions): UnaryCall<Empty, UserProfile> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, UserProfile>("unary", this._transport, method, opt, input);
    }
}
