/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "booking.proto" (package "svyne.booking", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TableBookingService } from "./booking";
import type { CreateEventTicketTypeRequest } from "./booking";
import type { CreateEventTableRequest } from "./booking";
import type { ListTablesResponse } from "./booking";
import type { LockTableRequest } from "./booking";
import type { AckResponse } from "./common";
import type { SaveEventLayoutRequest } from "./booking";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { EventLayout } from "./booking";
import type { UuidValue } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service svyne.booking.TableBookingService
 */
export interface ITableBookingServiceClient {
    /**
     * @generated from protobuf rpc: GetEventLayout(svyne.common.UuidValue) returns (svyne.booking.EventLayout);
     */
    getEventLayout(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, EventLayout>;
    /**
     * @generated from protobuf rpc: SaveEventLayout(svyne.booking.SaveEventLayoutRequest) returns (svyne.common.AckResponse);
     */
    saveEventLayout(input: SaveEventLayoutRequest, options?: RpcOptions): UnaryCall<SaveEventLayoutRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: LockTable(svyne.booking.LockTableRequest) returns (svyne.common.AckResponse);
     */
    lockTable(input: LockTableRequest, options?: RpcOptions): UnaryCall<LockTableRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ReleaseTableLock(svyne.booking.LockTableRequest) returns (svyne.common.AckResponse);
     */
    releaseTableLock(input: LockTableRequest, options?: RpcOptions): UnaryCall<LockTableRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ListTablesForEvent(svyne.common.UuidValue) returns (svyne.booking.ListTablesResponse);
     */
    listTablesForEvent(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListTablesResponse>;
    /**
     * @generated from protobuf rpc: CreateEventTable(svyne.booking.CreateEventTableRequest) returns (svyne.common.UuidValue);
     */
    createEventTable(input: CreateEventTableRequest, options?: RpcOptions): UnaryCall<CreateEventTableRequest, UuidValue>;
    /**
     * @generated from protobuf rpc: DeleteEventTable(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    deleteEventTable(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: CreateEventTicketType(svyne.booking.CreateEventTicketTypeRequest) returns (svyne.common.UuidValue);
     */
    createEventTicketType(input: CreateEventTicketTypeRequest, options?: RpcOptions): UnaryCall<CreateEventTicketTypeRequest, UuidValue>;
    /**
     * @generated from protobuf rpc: DeleteEventTicketType(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    deleteEventTicketType(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
}
/**
 * @generated from protobuf service svyne.booking.TableBookingService
 */
export class TableBookingServiceClient implements ITableBookingServiceClient, ServiceInfo {
    typeName = TableBookingService.typeName;
    methods = TableBookingService.methods;
    options = TableBookingService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetEventLayout(svyne.common.UuidValue) returns (svyne.booking.EventLayout);
     */
    getEventLayout(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, EventLayout> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, EventLayout>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveEventLayout(svyne.booking.SaveEventLayoutRequest) returns (svyne.common.AckResponse);
     */
    saveEventLayout(input: SaveEventLayoutRequest, options?: RpcOptions): UnaryCall<SaveEventLayoutRequest, AckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SaveEventLayoutRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LockTable(svyne.booking.LockTableRequest) returns (svyne.common.AckResponse);
     */
    lockTable(input: LockTableRequest, options?: RpcOptions): UnaryCall<LockTableRequest, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<LockTableRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReleaseTableLock(svyne.booking.LockTableRequest) returns (svyne.common.AckResponse);
     */
    releaseTableLock(input: LockTableRequest, options?: RpcOptions): UnaryCall<LockTableRequest, AckResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<LockTableRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTablesForEvent(svyne.common.UuidValue) returns (svyne.booking.ListTablesResponse);
     */
    listTablesForEvent(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListTablesResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, ListTablesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateEventTable(svyne.booking.CreateEventTableRequest) returns (svyne.common.UuidValue);
     */
    createEventTable(input: CreateEventTableRequest, options?: RpcOptions): UnaryCall<CreateEventTableRequest, UuidValue> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateEventTableRequest, UuidValue>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteEventTable(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    deleteEventTable(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateEventTicketType(svyne.booking.CreateEventTicketTypeRequest) returns (svyne.common.UuidValue);
     */
    createEventTicketType(input: CreateEventTicketTypeRequest, options?: RpcOptions): UnaryCall<CreateEventTicketTypeRequest, UuidValue> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateEventTicketTypeRequest, UuidValue>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteEventTicketType(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    deleteEventTicketType(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
}
