/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "booking.proto" (package "svyne.booking", syntax proto3)
// tslint:disable
import { AckResponse } from "./common";
import { UuidValue } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message svyne.booking.Table
 */
export interface Table {
    /**
     * @generated from protobuf field: string tables_id = 1;
     */
    tablesId: string;
    /**
     * @generated from protobuf field: string event_tables_id = 2;
     */
    eventTablesId: string;
    /**
     * @generated from protobuf field: string label = 3;
     */
    label: string;
    /**
     * @generated from protobuf field: int32 grid_row = 4;
     */
    gridRow: number;
    /**
     * @generated from protobuf field: int32 grid_col = 5;
     */
    gridCol: number;
    /**
     * @generated from protobuf field: int32 row_span = 6;
     */
    rowSpan: number;
    /**
     * @generated from protobuf field: int32 col_span = 7;
     */
    colSpan: number;
    /**
     * @generated from protobuf field: string status = 8;
     */
    status: string;
    /**
     * @generated from protobuf field: int32 price_cents = 9;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: int32 platform_fee_cents = 10;
     */
    platformFeeCents: number;
}
/**
 * @generated from protobuf message svyne.booking.EventLayout
 */
export interface EventLayout {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: int32 grid_rows = 2;
     */
    gridRows: number;
    /**
     * @generated from protobuf field: int32 grid_cols = 3;
     */
    gridCols: number;
    /**
     * @generated from protobuf field: repeated svyne.booking.Table tables = 4;
     */
    tables: Table[];
}
/**
 * @generated from protobuf message svyne.booking.SaveEventLayoutRequest
 */
export interface SaveEventLayoutRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: int32 grid_rows = 2;
     */
    gridRows: number;
    /**
     * @generated from protobuf field: int32 grid_cols = 3;
     */
    gridCols: number;
    /**
     * @generated from protobuf field: string tables_json = 4;
     */
    tablesJson: string;
    /**
     * @generated from protobuf field: repeated string locked_ids = 5;
     */
    lockedIds: string[];
}
/**
 * @generated from protobuf message svyne.booking.LockTableRequest
 */
export interface LockTableRequest {
    /**
     * @generated from protobuf field: string tables_id = 1;
     */
    tablesId: string;
}
/**
 * @generated from protobuf message svyne.booking.ListTablesResponse
 */
export interface ListTablesResponse {
    /**
     * @generated from protobuf field: repeated svyne.booking.Table tables = 1;
     */
    tables: Table[];
}
/**
 * @generated from protobuf message svyne.booking.CreateEventTableRequest
 */
export interface CreateEventTableRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string label = 2;
     */
    label: string;
    /**
     * @generated from protobuf field: int32 capacity = 3;
     */
    capacity: number;
    /**
     * @generated from protobuf field: string shape = 4;
     */
    shape: string;
    /**
     * @generated from protobuf field: string color = 5;
     */
    color: string;
    /**
     * @generated from protobuf field: int32 price_cents = 6;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: int32 platform_fee_cents = 7;
     */
    platformFeeCents: number;
    /**
     * @generated from protobuf field: string table_templates_id = 8;
     */
    tableTemplatesId: string;
}
/**
 * @generated from protobuf message svyne.booking.CreateEventTicketTypeRequest
 */
export interface CreateEventTicketTypeRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string label = 2;
     */
    label: string;
    /**
     * @generated from protobuf field: int32 price_cents = 3;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: int32 platform_fee_cents = 4;
     */
    platformFeeCents: number;
    /**
     * @generated from protobuf field: int32 max_quantity = 5;
     */
    maxQuantity: number;
    /**
     * @generated from protobuf field: int32 sort_order = 6;
     */
    sortOrder: number;
    /**
     * @generated from protobuf field: string description = 7;
     */
    description: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Table$Type extends MessageType<Table> {
    constructor() {
        super("svyne.booking.Table", [
            { no: 1, name: "tables_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "event_tables_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "grid_row", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "grid_col", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "row_span", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "col_span", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "platform_fee_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Table>): Table {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tablesId = "";
        message.eventTablesId = "";
        message.label = "";
        message.gridRow = 0;
        message.gridCol = 0;
        message.rowSpan = 0;
        message.colSpan = 0;
        message.status = "";
        message.priceCents = 0;
        message.platformFeeCents = 0;
        if (value !== undefined)
            reflectionMergePartial<Table>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Table): Table {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tables_id */ 1:
                    message.tablesId = reader.string();
                    break;
                case /* string event_tables_id */ 2:
                    message.eventTablesId = reader.string();
                    break;
                case /* string label */ 3:
                    message.label = reader.string();
                    break;
                case /* int32 grid_row */ 4:
                    message.gridRow = reader.int32();
                    break;
                case /* int32 grid_col */ 5:
                    message.gridCol = reader.int32();
                    break;
                case /* int32 row_span */ 6:
                    message.rowSpan = reader.int32();
                    break;
                case /* int32 col_span */ 7:
                    message.colSpan = reader.int32();
                    break;
                case /* string status */ 8:
                    message.status = reader.string();
                    break;
                case /* int32 price_cents */ 9:
                    message.priceCents = reader.int32();
                    break;
                case /* int32 platform_fee_cents */ 10:
                    message.platformFeeCents = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Table, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tables_id = 1; */
        if (message.tablesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tablesId);
        /* string event_tables_id = 2; */
        if (message.eventTablesId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventTablesId);
        /* string label = 3; */
        if (message.label !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.label);
        /* int32 grid_row = 4; */
        if (message.gridRow !== 0)
            writer.tag(4, WireType.Varint).int32(message.gridRow);
        /* int32 grid_col = 5; */
        if (message.gridCol !== 0)
            writer.tag(5, WireType.Varint).int32(message.gridCol);
        /* int32 row_span = 6; */
        if (message.rowSpan !== 0)
            writer.tag(6, WireType.Varint).int32(message.rowSpan);
        /* int32 col_span = 7; */
        if (message.colSpan !== 0)
            writer.tag(7, WireType.Varint).int32(message.colSpan);
        /* string status = 8; */
        if (message.status !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.status);
        /* int32 price_cents = 9; */
        if (message.priceCents !== 0)
            writer.tag(9, WireType.Varint).int32(message.priceCents);
        /* int32 platform_fee_cents = 10; */
        if (message.platformFeeCents !== 0)
            writer.tag(10, WireType.Varint).int32(message.platformFeeCents);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.Table
 */
export const Table = new Table$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EventLayout$Type extends MessageType<EventLayout> {
    constructor() {
        super("svyne.booking.EventLayout", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "grid_rows", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "grid_cols", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "tables", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Table }
        ]);
    }
    create(value?: PartialMessage<EventLayout>): EventLayout {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.gridRows = 0;
        message.gridCols = 0;
        message.tables = [];
        if (value !== undefined)
            reflectionMergePartial<EventLayout>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventLayout): EventLayout {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* int32 grid_rows */ 2:
                    message.gridRows = reader.int32();
                    break;
                case /* int32 grid_cols */ 3:
                    message.gridCols = reader.int32();
                    break;
                case /* repeated svyne.booking.Table tables */ 4:
                    message.tables.push(Table.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventLayout, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* int32 grid_rows = 2; */
        if (message.gridRows !== 0)
            writer.tag(2, WireType.Varint).int32(message.gridRows);
        /* int32 grid_cols = 3; */
        if (message.gridCols !== 0)
            writer.tag(3, WireType.Varint).int32(message.gridCols);
        /* repeated svyne.booking.Table tables = 4; */
        for (let i = 0; i < message.tables.length; i++)
            Table.internalBinaryWrite(message.tables[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.EventLayout
 */
export const EventLayout = new EventLayout$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SaveEventLayoutRequest$Type extends MessageType<SaveEventLayoutRequest> {
    constructor() {
        super("svyne.booking.SaveEventLayoutRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "grid_rows", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "grid_cols", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "tables_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "locked_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SaveEventLayoutRequest>): SaveEventLayoutRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.gridRows = 0;
        message.gridCols = 0;
        message.tablesJson = "";
        message.lockedIds = [];
        if (value !== undefined)
            reflectionMergePartial<SaveEventLayoutRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SaveEventLayoutRequest): SaveEventLayoutRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* int32 grid_rows */ 2:
                    message.gridRows = reader.int32();
                    break;
                case /* int32 grid_cols */ 3:
                    message.gridCols = reader.int32();
                    break;
                case /* string tables_json */ 4:
                    message.tablesJson = reader.string();
                    break;
                case /* repeated string locked_ids */ 5:
                    message.lockedIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SaveEventLayoutRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* int32 grid_rows = 2; */
        if (message.gridRows !== 0)
            writer.tag(2, WireType.Varint).int32(message.gridRows);
        /* int32 grid_cols = 3; */
        if (message.gridCols !== 0)
            writer.tag(3, WireType.Varint).int32(message.gridCols);
        /* string tables_json = 4; */
        if (message.tablesJson !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.tablesJson);
        /* repeated string locked_ids = 5; */
        for (let i = 0; i < message.lockedIds.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.lockedIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.SaveEventLayoutRequest
 */
export const SaveEventLayoutRequest = new SaveEventLayoutRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LockTableRequest$Type extends MessageType<LockTableRequest> {
    constructor() {
        super("svyne.booking.LockTableRequest", [
            { no: 1, name: "tables_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LockTableRequest>): LockTableRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tablesId = "";
        if (value !== undefined)
            reflectionMergePartial<LockTableRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LockTableRequest): LockTableRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tables_id */ 1:
                    message.tablesId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LockTableRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tables_id = 1; */
        if (message.tablesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tablesId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.LockTableRequest
 */
export const LockTableRequest = new LockTableRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListTablesResponse$Type extends MessageType<ListTablesResponse> {
    constructor() {
        super("svyne.booking.ListTablesResponse", [
            { no: 1, name: "tables", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Table }
        ]);
    }
    create(value?: PartialMessage<ListTablesResponse>): ListTablesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tables = [];
        if (value !== undefined)
            reflectionMergePartial<ListTablesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListTablesResponse): ListTablesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.booking.Table tables */ 1:
                    message.tables.push(Table.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListTablesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.booking.Table tables = 1; */
        for (let i = 0; i < message.tables.length; i++)
            Table.internalBinaryWrite(message.tables[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.ListTablesResponse
 */
export const ListTablesResponse = new ListTablesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateEventTableRequest$Type extends MessageType<CreateEventTableRequest> {
    constructor() {
        super("svyne.booking.CreateEventTableRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "shape", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "platform_fee_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "table_templates_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateEventTableRequest>): CreateEventTableRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.label = "";
        message.capacity = 0;
        message.shape = "";
        message.color = "";
        message.priceCents = 0;
        message.platformFeeCents = 0;
        message.tableTemplatesId = "";
        if (value !== undefined)
            reflectionMergePartial<CreateEventTableRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateEventTableRequest): CreateEventTableRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string label */ 2:
                    message.label = reader.string();
                    break;
                case /* int32 capacity */ 3:
                    message.capacity = reader.int32();
                    break;
                case /* string shape */ 4:
                    message.shape = reader.string();
                    break;
                case /* string color */ 5:
                    message.color = reader.string();
                    break;
                case /* int32 price_cents */ 6:
                    message.priceCents = reader.int32();
                    break;
                case /* int32 platform_fee_cents */ 7:
                    message.platformFeeCents = reader.int32();
                    break;
                case /* string table_templates_id */ 8:
                    message.tableTemplatesId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateEventTableRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string label = 2; */
        if (message.label !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.label);
        /* int32 capacity = 3; */
        if (message.capacity !== 0)
            writer.tag(3, WireType.Varint).int32(message.capacity);
        /* string shape = 4; */
        if (message.shape !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.shape);
        /* string color = 5; */
        if (message.color !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.color);
        /* int32 price_cents = 6; */
        if (message.priceCents !== 0)
            writer.tag(6, WireType.Varint).int32(message.priceCents);
        /* int32 platform_fee_cents = 7; */
        if (message.platformFeeCents !== 0)
            writer.tag(7, WireType.Varint).int32(message.platformFeeCents);
        /* string table_templates_id = 8; */
        if (message.tableTemplatesId !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.tableTemplatesId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.CreateEventTableRequest
 */
export const CreateEventTableRequest = new CreateEventTableRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateEventTicketTypeRequest$Type extends MessageType<CreateEventTicketTypeRequest> {
    constructor() {
        super("svyne.booking.CreateEventTicketTypeRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "platform_fee_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "max_quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "sort_order", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateEventTicketTypeRequest>): CreateEventTicketTypeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.label = "";
        message.priceCents = 0;
        message.platformFeeCents = 0;
        message.maxQuantity = 0;
        message.sortOrder = 0;
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<CreateEventTicketTypeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateEventTicketTypeRequest): CreateEventTicketTypeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string label */ 2:
                    message.label = reader.string();
                    break;
                case /* int32 price_cents */ 3:
                    message.priceCents = reader.int32();
                    break;
                case /* int32 platform_fee_cents */ 4:
                    message.platformFeeCents = reader.int32();
                    break;
                case /* int32 max_quantity */ 5:
                    message.maxQuantity = reader.int32();
                    break;
                case /* int32 sort_order */ 6:
                    message.sortOrder = reader.int32();
                    break;
                case /* string description */ 7:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateEventTicketTypeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string label = 2; */
        if (message.label !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.label);
        /* int32 price_cents = 3; */
        if (message.priceCents !== 0)
            writer.tag(3, WireType.Varint).int32(message.priceCents);
        /* int32 platform_fee_cents = 4; */
        if (message.platformFeeCents !== 0)
            writer.tag(4, WireType.Varint).int32(message.platformFeeCents);
        /* int32 max_quantity = 5; */
        if (message.maxQuantity !== 0)
            writer.tag(5, WireType.Varint).int32(message.maxQuantity);
        /* int32 sort_order = 6; */
        if (message.sortOrder !== 0)
            writer.tag(6, WireType.Varint).int32(message.sortOrder);
        /* string description = 7; */
        if (message.description !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.CreateEventTicketTypeRequest
 */
export const CreateEventTicketTypeRequest = new CreateEventTicketTypeRequest$Type();
/**
 * @generated ServiceType for protobuf service svyne.booking.TableBookingService
 */
export const TableBookingService = new ServiceType("svyne.booking.TableBookingService", [
    { name: "GetEventLayout", options: {}, I: UuidValue, O: EventLayout },
    { name: "SaveEventLayout", options: {}, I: SaveEventLayoutRequest, O: AckResponse },
    { name: "LockTable", options: {}, I: LockTableRequest, O: AckResponse },
    { name: "ReleaseTableLock", options: {}, I: LockTableRequest, O: AckResponse },
    { name: "ListTablesForEvent", options: {}, I: UuidValue, O: ListTablesResponse },
    { name: "CreateEventTable", options: {}, I: CreateEventTableRequest, O: UuidValue },
    { name: "DeleteEventTable", options: {}, I: UuidValue, O: AckResponse },
    { name: "CreateEventTicketType", options: {}, I: CreateEventTicketTypeRequest, O: UuidValue },
    { name: "DeleteEventTicketType", options: {}, I: UuidValue, O: AckResponse }
]);
