/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "purchase.proto" (package "svyne.purchase", syntax proto3)
// tslint:disable
import { CheckInService } from "./purchase";
import type { CheckInStats } from "./purchase";
import type { ScanResponse } from "./purchase";
import type { ScanRequest } from "./purchase";
import { TicketService } from "./purchase";
import type { ListTicketsResponse } from "./purchase";
import type { InviteTicketRequest } from "./purchase";
import type { ClaimTicketRequest } from "./purchase";
import type { Ticket } from "./purchase";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PurchaseService } from "./purchase";
import type { PurchaseStats } from "./purchase";
import type { ListPurchasesResponse } from "./purchase";
import type { ListPurchasesRequest } from "./purchase";
import type { Purchase } from "./purchase";
import type { UuidValue } from "./common";
import type { AckResponse } from "./common";
import type { ConfirmPurchaseRequest } from "./purchase";
import type { ReserveOpenCapacityRequest } from "./purchase";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreatePurchaseResponse } from "./purchase";
import type { CreatePurchaseRequest } from "./purchase";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service svyne.purchase.PurchaseService
 */
export interface IPurchaseServiceClient {
    /**
     * @generated from protobuf rpc: CreatePurchase(svyne.purchase.CreatePurchaseRequest) returns (svyne.purchase.CreatePurchaseResponse);
     */
    createPurchase(input: CreatePurchaseRequest, options?: RpcOptions): UnaryCall<CreatePurchaseRequest, CreatePurchaseResponse>;
    /**
     * @generated from protobuf rpc: ReserveOpenCapacity(svyne.purchase.ReserveOpenCapacityRequest) returns (svyne.purchase.CreatePurchaseResponse);
     */
    reserveOpenCapacity(input: ReserveOpenCapacityRequest, options?: RpcOptions): UnaryCall<ReserveOpenCapacityRequest, CreatePurchaseResponse>;
    /**
     * @generated from protobuf rpc: ConfirmPurchase(svyne.purchase.ConfirmPurchaseRequest) returns (svyne.common.AckResponse);
     */
    confirmPurchase(input: ConfirmPurchaseRequest, options?: RpcOptions): UnaryCall<ConfirmPurchaseRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: CancelPurchase(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    cancelPurchase(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: RefundPurchase(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    refundPurchase(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: GetPurchase(svyne.common.UuidValue) returns (svyne.purchase.Purchase);
     */
    getPurchase(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Purchase>;
    /**
     * @generated from protobuf rpc: ListPurchases(svyne.purchase.ListPurchasesRequest) returns (svyne.purchase.ListPurchasesResponse);
     */
    listPurchases(input: ListPurchasesRequest, options?: RpcOptions): UnaryCall<ListPurchasesRequest, ListPurchasesResponse>;
    /**
     * @generated from protobuf rpc: GetPurchaseStats(svyne.common.UuidValue) returns (svyne.purchase.PurchaseStats);
     */
    getPurchaseStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, PurchaseStats>;
}
/**
 * @generated from protobuf service svyne.purchase.PurchaseService
 */
export class PurchaseServiceClient implements IPurchaseServiceClient, ServiceInfo {
    typeName = PurchaseService.typeName;
    methods = PurchaseService.methods;
    options = PurchaseService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePurchase(svyne.purchase.CreatePurchaseRequest) returns (svyne.purchase.CreatePurchaseResponse);
     */
    createPurchase(input: CreatePurchaseRequest, options?: RpcOptions): UnaryCall<CreatePurchaseRequest, CreatePurchaseResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePurchaseRequest, CreatePurchaseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReserveOpenCapacity(svyne.purchase.ReserveOpenCapacityRequest) returns (svyne.purchase.CreatePurchaseResponse);
     */
    reserveOpenCapacity(input: ReserveOpenCapacityRequest, options?: RpcOptions): UnaryCall<ReserveOpenCapacityRequest, CreatePurchaseResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReserveOpenCapacityRequest, CreatePurchaseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ConfirmPurchase(svyne.purchase.ConfirmPurchaseRequest) returns (svyne.common.AckResponse);
     */
    confirmPurchase(input: ConfirmPurchaseRequest, options?: RpcOptions): UnaryCall<ConfirmPurchaseRequest, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ConfirmPurchaseRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelPurchase(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    cancelPurchase(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefundPurchase(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    refundPurchase(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPurchase(svyne.common.UuidValue) returns (svyne.purchase.Purchase);
     */
    getPurchase(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Purchase> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, Purchase>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListPurchases(svyne.purchase.ListPurchasesRequest) returns (svyne.purchase.ListPurchasesResponse);
     */
    listPurchases(input: ListPurchasesRequest, options?: RpcOptions): UnaryCall<ListPurchasesRequest, ListPurchasesResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListPurchasesRequest, ListPurchasesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPurchaseStats(svyne.common.UuidValue) returns (svyne.purchase.PurchaseStats);
     */
    getPurchaseStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, PurchaseStats> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, PurchaseStats>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service svyne.purchase.TicketService
 */
export interface ITicketServiceClient {
    /**
     * @generated from protobuf rpc: GetTicket(svyne.common.UuidValue) returns (svyne.purchase.Ticket);
     */
    getTicket(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Ticket>;
    /**
     * @generated from protobuf rpc: ClaimTicket(svyne.purchase.ClaimTicketRequest) returns (svyne.common.AckResponse);
     */
    claimTicket(input: ClaimTicketRequest, options?: RpcOptions): UnaryCall<ClaimTicketRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: InviteTicket(svyne.purchase.InviteTicketRequest) returns (svyne.common.AckResponse);
     */
    inviteTicket(input: InviteTicketRequest, options?: RpcOptions): UnaryCall<InviteTicketRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ListPurchaseTickets(svyne.common.UuidValue) returns (svyne.purchase.ListTicketsResponse);
     */
    listPurchaseTickets(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListTicketsResponse>;
}
/**
 * @generated from protobuf service svyne.purchase.TicketService
 */
export class TicketServiceClient implements ITicketServiceClient, ServiceInfo {
    typeName = TicketService.typeName;
    methods = TicketService.methods;
    options = TicketService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetTicket(svyne.common.UuidValue) returns (svyne.purchase.Ticket);
     */
    getTicket(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Ticket> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, Ticket>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ClaimTicket(svyne.purchase.ClaimTicketRequest) returns (svyne.common.AckResponse);
     */
    claimTicket(input: ClaimTicketRequest, options?: RpcOptions): UnaryCall<ClaimTicketRequest, AckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClaimTicketRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InviteTicket(svyne.purchase.InviteTicketRequest) returns (svyne.common.AckResponse);
     */
    inviteTicket(input: InviteTicketRequest, options?: RpcOptions): UnaryCall<InviteTicketRequest, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<InviteTicketRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListPurchaseTickets(svyne.common.UuidValue) returns (svyne.purchase.ListTicketsResponse);
     */
    listPurchaseTickets(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListTicketsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, ListTicketsResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service svyne.purchase.CheckInService
 */
export interface ICheckInServiceClient {
    /**
     * @generated from protobuf rpc: Scan(svyne.purchase.ScanRequest) returns (svyne.purchase.ScanResponse);
     */
    scan(input: ScanRequest, options?: RpcOptions): UnaryCall<ScanRequest, ScanResponse>;
    /**
     * @generated from protobuf rpc: GetCheckInStats(svyne.common.UuidValue) returns (svyne.purchase.CheckInStats);
     */
    getCheckInStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, CheckInStats>;
}
/**
 * @generated from protobuf service svyne.purchase.CheckInService
 */
export class CheckInServiceClient implements ICheckInServiceClient, ServiceInfo {
    typeName = CheckInService.typeName;
    methods = CheckInService.methods;
    options = CheckInService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Scan(svyne.purchase.ScanRequest) returns (svyne.purchase.ScanResponse);
     */
    scan(input: ScanRequest, options?: RpcOptions): UnaryCall<ScanRequest, ScanResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ScanRequest, ScanResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCheckInStats(svyne.common.UuidValue) returns (svyne.purchase.CheckInStats);
     */
    getCheckInStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, CheckInStats> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, CheckInStats>("unary", this._transport, method, opt, input);
    }
}
