/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "purchase.proto" (package "svyne.purchase", syntax proto3)
// tslint:disable
import { UuidValue } from "./common";
import { AckResponse } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PageMeta } from "./common";
import { PageRequest } from "./common";
/**
 * @generated from protobuf message svyne.purchase.Purchase
 */
export interface Purchase {
    /**
     * @generated from protobuf field: string purchases_id = 1;
     */
    purchasesId: string;
    /**
     * @generated from protobuf field: string tenants_id = 2;
     */
    tenantsId: string;
    /**
     * @generated from protobuf field: string purchase_number = 3;
     */
    purchaseNumber: string;
    /**
     * @generated from protobuf field: string status = 4;
     */
    status: string;
    /**
     * @generated from protobuf field: string users_id = 5;
     */
    usersId: string;
    /**
     * @generated from protobuf field: string events_id = 6;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: int32 subtotal_cents = 7;
     */
    subtotalCents: number;
    /**
     * @generated from protobuf field: int32 fee_cents = 8;
     */
    feeCents: number;
    /**
     * @generated from protobuf field: int32 total_cents = 9;
     */
    totalCents: number;
    /**
     * @generated from protobuf field: int32 seats_reserved = 10;
     */
    seatsReserved: number;
}
/**
 * @generated from protobuf message svyne.purchase.CreatePurchaseRequest
 */
export interface CreatePurchaseRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string tables_id = 2;
     */
    tablesId: string;
    /**
     * @generated from protobuf field: int32 seats = 3;
     */
    seats: number;
    /**
     * @generated from protobuf field: string event_ticket_types_id = 4;
     */
    eventTicketTypesId: string;
    /**
     * @generated from protobuf field: int32 subtotal_cents = 5;
     */
    subtotalCents: number;
    /**
     * @generated from protobuf field: int32 fee_cents = 6;
     */
    feeCents: number;
    /**
     * @generated from protobuf field: int32 total_cents = 7;
     */
    totalCents: number;
}
/**
 * @generated from protobuf message svyne.purchase.ReserveOpenCapacityRequest
 */
export interface ReserveOpenCapacityRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: int32 seats = 2;
     */
    seats: number;
    /**
     * @generated from protobuf field: string event_ticket_types_id = 3;
     */
    eventTicketTypesId: string;
    /**
     * @generated from protobuf field: int32 subtotal_cents = 4;
     */
    subtotalCents: number;
    /**
     * @generated from protobuf field: int32 fee_cents = 5;
     */
    feeCents: number;
    /**
     * @generated from protobuf field: int32 total_cents = 6;
     */
    totalCents: number;
}
/**
 * @generated from protobuf message svyne.purchase.CreatePurchaseResponse
 */
export interface CreatePurchaseResponse {
    /**
     * @generated from protobuf field: string purchases_id = 1;
     */
    purchasesId: string;
    /**
     * @generated from protobuf field: string purchase_number = 2;
     */
    purchaseNumber: string;
}
/**
 * @generated from protobuf message svyne.purchase.ConfirmPurchaseRequest
 */
export interface ConfirmPurchaseRequest {
    /**
     * @generated from protobuf field: string purchases_id = 1;
     */
    purchasesId: string;
    /**
     * @generated from protobuf field: string qr_token = 2;
     */
    qrToken: string;
}
/**
 * @generated from protobuf message svyne.purchase.ListPurchasesRequest
 */
export interface ListPurchasesRequest {
    /**
     * @generated from protobuf field: svyne.common.PageRequest page = 1;
     */
    page?: PageRequest;
    /**
     * @generated from protobuf field: string events_id = 2;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string status = 3;
     */
    status: string;
}
/**
 * @generated from protobuf message svyne.purchase.ListPurchasesResponse
 */
export interface ListPurchasesResponse {
    /**
     * @generated from protobuf field: repeated svyne.purchase.Purchase purchases = 1;
     */
    purchases: Purchase[];
    /**
     * @generated from protobuf field: svyne.common.PageMeta meta = 2;
     */
    meta?: PageMeta;
}
/**
 * @generated from protobuf message svyne.purchase.PurchaseStats
 */
export interface PurchaseStats {
    /**
     * @generated from protobuf field: int32 total = 1;
     */
    total: number;
    /**
     * @generated from protobuf field: int32 paid = 2;
     */
    paid: number;
    /**
     * @generated from protobuf field: int32 checked_in = 3;
     */
    checkedIn: number;
    /**
     * @generated from protobuf field: int64 revenue_cents = 4;
     */
    revenueCents: string;
}
/**
 * @generated from protobuf message svyne.purchase.Ticket
 */
export interface Ticket {
    /**
     * @generated from protobuf field: string purchase_tickets_id = 1;
     */
    purchaseTicketsId: string;
    /**
     * @generated from protobuf field: string ticket_code = 2;
     */
    ticketCode: string;
    /**
     * @generated from protobuf field: string qr_token = 3;
     */
    qrToken: string;
    /**
     * @generated from protobuf field: int32 seat_number = 4;
     */
    seatNumber: number;
    /**
     * @generated from protobuf field: string status = 5;
     */
    status: string;
    /**
     * @generated from protobuf field: string guest_users_id = 6;
     */
    guestUsersId: string;
}
/**
 * @generated from protobuf message svyne.purchase.ClaimTicketRequest
 */
export interface ClaimTicketRequest {
    /**
     * @generated from protobuf field: string token = 1;
     */
    token: string;
}
/**
 * @generated from protobuf message svyne.purchase.InviteTicketRequest
 */
export interface InviteTicketRequest {
    /**
     * @generated from protobuf field: string purchase_tickets_id = 1;
     */
    purchaseTicketsId: string;
    /**
     * @generated from protobuf field: string email = 2;
     */
    email: string;
}
/**
 * @generated from protobuf message svyne.purchase.ListTicketsResponse
 */
export interface ListTicketsResponse {
    /**
     * @generated from protobuf field: repeated svyne.purchase.Ticket tickets = 1;
     */
    tickets: Ticket[];
}
/**
 * @generated from protobuf message svyne.purchase.ScanRequest
 */
export interface ScanRequest {
    /**
     * @generated from protobuf field: string qr_token = 1;
     */
    qrToken: string;
    /**
     * @generated from protobuf field: string events_id = 2;
     */
    eventsId: string;
}
/**
 * @generated from protobuf message svyne.purchase.ScanResponse
 */
export interface ScanResponse {
    /**
     * @generated from protobuf field: bool valid = 1;
     */
    valid: boolean;
    /**
     * @generated from protobuf field: string status = 2;
     */
    status: string;
    /**
     * @generated from protobuf field: string holder_name = 3;
     */
    holderName: string;
    /**
     * @generated from protobuf field: string message = 4;
     */
    message: string;
}
/**
 * @generated from protobuf message svyne.purchase.CheckInStats
 */
export interface CheckInStats {
    /**
     * @generated from protobuf field: int32 total = 1;
     */
    total: number;
    /**
     * @generated from protobuf field: int32 checked_in = 2;
     */
    checkedIn: number;
    /**
     * @generated from protobuf field: int32 remaining = 3;
     */
    remaining: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Purchase$Type extends MessageType<Purchase> {
    constructor() {
        super("svyne.purchase.Purchase", [
            { no: 1, name: "purchases_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tenants_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "purchase_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "users_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "subtotal_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "fee_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "total_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "seats_reserved", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Purchase>): Purchase {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.purchasesId = "";
        message.tenantsId = "";
        message.purchaseNumber = "";
        message.status = "";
        message.usersId = "";
        message.eventsId = "";
        message.subtotalCents = 0;
        message.feeCents = 0;
        message.totalCents = 0;
        message.seatsReserved = 0;
        if (value !== undefined)
            reflectionMergePartial<Purchase>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Purchase): Purchase {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string purchases_id */ 1:
                    message.purchasesId = reader.string();
                    break;
                case /* string tenants_id */ 2:
                    message.tenantsId = reader.string();
                    break;
                case /* string purchase_number */ 3:
                    message.purchaseNumber = reader.string();
                    break;
                case /* string status */ 4:
                    message.status = reader.string();
                    break;
                case /* string users_id */ 5:
                    message.usersId = reader.string();
                    break;
                case /* string events_id */ 6:
                    message.eventsId = reader.string();
                    break;
                case /* int32 subtotal_cents */ 7:
                    message.subtotalCents = reader.int32();
                    break;
                case /* int32 fee_cents */ 8:
                    message.feeCents = reader.int32();
                    break;
                case /* int32 total_cents */ 9:
                    message.totalCents = reader.int32();
                    break;
                case /* int32 seats_reserved */ 10:
                    message.seatsReserved = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Purchase, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string purchases_id = 1; */
        if (message.purchasesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.purchasesId);
        /* string tenants_id = 2; */
        if (message.tenantsId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tenantsId);
        /* string purchase_number = 3; */
        if (message.purchaseNumber !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.purchaseNumber);
        /* string status = 4; */
        if (message.status !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.status);
        /* string users_id = 5; */
        if (message.usersId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.usersId);
        /* string events_id = 6; */
        if (message.eventsId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.eventsId);
        /* int32 subtotal_cents = 7; */
        if (message.subtotalCents !== 0)
            writer.tag(7, WireType.Varint).int32(message.subtotalCents);
        /* int32 fee_cents = 8; */
        if (message.feeCents !== 0)
            writer.tag(8, WireType.Varint).int32(message.feeCents);
        /* int32 total_cents = 9; */
        if (message.totalCents !== 0)
            writer.tag(9, WireType.Varint).int32(message.totalCents);
        /* int32 seats_reserved = 10; */
        if (message.seatsReserved !== 0)
            writer.tag(10, WireType.Varint).int32(message.seatsReserved);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.Purchase
 */
export const Purchase = new Purchase$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePurchaseRequest$Type extends MessageType<CreatePurchaseRequest> {
    constructor() {
        super("svyne.purchase.CreatePurchaseRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tables_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "seats", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "event_ticket_types_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "subtotal_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "fee_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "total_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CreatePurchaseRequest>): CreatePurchaseRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.tablesId = "";
        message.seats = 0;
        message.eventTicketTypesId = "";
        message.subtotalCents = 0;
        message.feeCents = 0;
        message.totalCents = 0;
        if (value !== undefined)
            reflectionMergePartial<CreatePurchaseRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePurchaseRequest): CreatePurchaseRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string tables_id */ 2:
                    message.tablesId = reader.string();
                    break;
                case /* int32 seats */ 3:
                    message.seats = reader.int32();
                    break;
                case /* string event_ticket_types_id */ 4:
                    message.eventTicketTypesId = reader.string();
                    break;
                case /* int32 subtotal_cents */ 5:
                    message.subtotalCents = reader.int32();
                    break;
                case /* int32 fee_cents */ 6:
                    message.feeCents = reader.int32();
                    break;
                case /* int32 total_cents */ 7:
                    message.totalCents = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePurchaseRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string tables_id = 2; */
        if (message.tablesId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tablesId);
        /* int32 seats = 3; */
        if (message.seats !== 0)
            writer.tag(3, WireType.Varint).int32(message.seats);
        /* string event_ticket_types_id = 4; */
        if (message.eventTicketTypesId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.eventTicketTypesId);
        /* int32 subtotal_cents = 5; */
        if (message.subtotalCents !== 0)
            writer.tag(5, WireType.Varint).int32(message.subtotalCents);
        /* int32 fee_cents = 6; */
        if (message.feeCents !== 0)
            writer.tag(6, WireType.Varint).int32(message.feeCents);
        /* int32 total_cents = 7; */
        if (message.totalCents !== 0)
            writer.tag(7, WireType.Varint).int32(message.totalCents);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.CreatePurchaseRequest
 */
export const CreatePurchaseRequest = new CreatePurchaseRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReserveOpenCapacityRequest$Type extends MessageType<ReserveOpenCapacityRequest> {
    constructor() {
        super("svyne.purchase.ReserveOpenCapacityRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "seats", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "event_ticket_types_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "subtotal_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "fee_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "total_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ReserveOpenCapacityRequest>): ReserveOpenCapacityRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.seats = 0;
        message.eventTicketTypesId = "";
        message.subtotalCents = 0;
        message.feeCents = 0;
        message.totalCents = 0;
        if (value !== undefined)
            reflectionMergePartial<ReserveOpenCapacityRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReserveOpenCapacityRequest): ReserveOpenCapacityRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* int32 seats */ 2:
                    message.seats = reader.int32();
                    break;
                case /* string event_ticket_types_id */ 3:
                    message.eventTicketTypesId = reader.string();
                    break;
                case /* int32 subtotal_cents */ 4:
                    message.subtotalCents = reader.int32();
                    break;
                case /* int32 fee_cents */ 5:
                    message.feeCents = reader.int32();
                    break;
                case /* int32 total_cents */ 6:
                    message.totalCents = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReserveOpenCapacityRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* int32 seats = 2; */
        if (message.seats !== 0)
            writer.tag(2, WireType.Varint).int32(message.seats);
        /* string event_ticket_types_id = 3; */
        if (message.eventTicketTypesId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.eventTicketTypesId);
        /* int32 subtotal_cents = 4; */
        if (message.subtotalCents !== 0)
            writer.tag(4, WireType.Varint).int32(message.subtotalCents);
        /* int32 fee_cents = 5; */
        if (message.feeCents !== 0)
            writer.tag(5, WireType.Varint).int32(message.feeCents);
        /* int32 total_cents = 6; */
        if (message.totalCents !== 0)
            writer.tag(6, WireType.Varint).int32(message.totalCents);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.ReserveOpenCapacityRequest
 */
export const ReserveOpenCapacityRequest = new ReserveOpenCapacityRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePurchaseResponse$Type extends MessageType<CreatePurchaseResponse> {
    constructor() {
        super("svyne.purchase.CreatePurchaseResponse", [
            { no: 1, name: "purchases_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "purchase_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreatePurchaseResponse>): CreatePurchaseResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.purchasesId = "";
        message.purchaseNumber = "";
        if (value !== undefined)
            reflectionMergePartial<CreatePurchaseResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePurchaseResponse): CreatePurchaseResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string purchases_id */ 1:
                    message.purchasesId = reader.string();
                    break;
                case /* string purchase_number */ 2:
                    message.purchaseNumber = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePurchaseResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string purchases_id = 1; */
        if (message.purchasesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.purchasesId);
        /* string purchase_number = 2; */
        if (message.purchaseNumber !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.purchaseNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.CreatePurchaseResponse
 */
export const CreatePurchaseResponse = new CreatePurchaseResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfirmPurchaseRequest$Type extends MessageType<ConfirmPurchaseRequest> {
    constructor() {
        super("svyne.purchase.ConfirmPurchaseRequest", [
            { no: 1, name: "purchases_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "qr_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConfirmPurchaseRequest>): ConfirmPurchaseRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.purchasesId = "";
        message.qrToken = "";
        if (value !== undefined)
            reflectionMergePartial<ConfirmPurchaseRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfirmPurchaseRequest): ConfirmPurchaseRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string purchases_id */ 1:
                    message.purchasesId = reader.string();
                    break;
                case /* string qr_token */ 2:
                    message.qrToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfirmPurchaseRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string purchases_id = 1; */
        if (message.purchasesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.purchasesId);
        /* string qr_token = 2; */
        if (message.qrToken !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.qrToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.ConfirmPurchaseRequest
 */
export const ConfirmPurchaseRequest = new ConfirmPurchaseRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListPurchasesRequest$Type extends MessageType<ListPurchasesRequest> {
    constructor() {
        super("svyne.purchase.ListPurchasesRequest", [
            { no: 1, name: "page", kind: "message", T: () => PageRequest },
            { no: 2, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListPurchasesRequest>): ListPurchasesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<ListPurchasesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListPurchasesRequest): ListPurchasesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* svyne.common.PageRequest page */ 1:
                    message.page = PageRequest.internalBinaryRead(reader, reader.uint32(), options, message.page);
                    break;
                case /* string events_id */ 2:
                    message.eventsId = reader.string();
                    break;
                case /* string status */ 3:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListPurchasesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* svyne.common.PageRequest page = 1; */
        if (message.page)
            PageRequest.internalBinaryWrite(message.page, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string events_id = 2; */
        if (message.eventsId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventsId);
        /* string status = 3; */
        if (message.status !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.ListPurchasesRequest
 */
export const ListPurchasesRequest = new ListPurchasesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListPurchasesResponse$Type extends MessageType<ListPurchasesResponse> {
    constructor() {
        super("svyne.purchase.ListPurchasesResponse", [
            { no: 1, name: "purchases", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Purchase },
            { no: 2, name: "meta", kind: "message", T: () => PageMeta }
        ]);
    }
    create(value?: PartialMessage<ListPurchasesResponse>): ListPurchasesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.purchases = [];
        if (value !== undefined)
            reflectionMergePartial<ListPurchasesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListPurchasesResponse): ListPurchasesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.purchase.Purchase purchases */ 1:
                    message.purchases.push(Purchase.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* svyne.common.PageMeta meta */ 2:
                    message.meta = PageMeta.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListPurchasesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.purchase.Purchase purchases = 1; */
        for (let i = 0; i < message.purchases.length; i++)
            Purchase.internalBinaryWrite(message.purchases[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* svyne.common.PageMeta meta = 2; */
        if (message.meta)
            PageMeta.internalBinaryWrite(message.meta, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.ListPurchasesResponse
 */
export const ListPurchasesResponse = new ListPurchasesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PurchaseStats$Type extends MessageType<PurchaseStats> {
    constructor() {
        super("svyne.purchase.PurchaseStats", [
            { no: 1, name: "total", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "paid", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "checked_in", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "revenue_cents", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<PurchaseStats>): PurchaseStats {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.total = 0;
        message.paid = 0;
        message.checkedIn = 0;
        message.revenueCents = "0";
        if (value !== undefined)
            reflectionMergePartial<PurchaseStats>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PurchaseStats): PurchaseStats {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 total */ 1:
                    message.total = reader.int32();
                    break;
                case /* int32 paid */ 2:
                    message.paid = reader.int32();
                    break;
                case /* int32 checked_in */ 3:
                    message.checkedIn = reader.int32();
                    break;
                case /* int64 revenue_cents */ 4:
                    message.revenueCents = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PurchaseStats, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 total = 1; */
        if (message.total !== 0)
            writer.tag(1, WireType.Varint).int32(message.total);
        /* int32 paid = 2; */
        if (message.paid !== 0)
            writer.tag(2, WireType.Varint).int32(message.paid);
        /* int32 checked_in = 3; */
        if (message.checkedIn !== 0)
            writer.tag(3, WireType.Varint).int32(message.checkedIn);
        /* int64 revenue_cents = 4; */
        if (message.revenueCents !== "0")
            writer.tag(4, WireType.Varint).int64(message.revenueCents);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.PurchaseStats
 */
export const PurchaseStats = new PurchaseStats$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Ticket$Type extends MessageType<Ticket> {
    constructor() {
        super("svyne.purchase.Ticket", [
            { no: 1, name: "purchase_tickets_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ticket_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "qr_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "seat_number", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "guest_users_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Ticket>): Ticket {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.purchaseTicketsId = "";
        message.ticketCode = "";
        message.qrToken = "";
        message.seatNumber = 0;
        message.status = "";
        message.guestUsersId = "";
        if (value !== undefined)
            reflectionMergePartial<Ticket>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Ticket): Ticket {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string purchase_tickets_id */ 1:
                    message.purchaseTicketsId = reader.string();
                    break;
                case /* string ticket_code */ 2:
                    message.ticketCode = reader.string();
                    break;
                case /* string qr_token */ 3:
                    message.qrToken = reader.string();
                    break;
                case /* int32 seat_number */ 4:
                    message.seatNumber = reader.int32();
                    break;
                case /* string status */ 5:
                    message.status = reader.string();
                    break;
                case /* string guest_users_id */ 6:
                    message.guestUsersId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Ticket, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string purchase_tickets_id = 1; */
        if (message.purchaseTicketsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.purchaseTicketsId);
        /* string ticket_code = 2; */
        if (message.ticketCode !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.ticketCode);
        /* string qr_token = 3; */
        if (message.qrToken !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.qrToken);
        /* int32 seat_number = 4; */
        if (message.seatNumber !== 0)
            writer.tag(4, WireType.Varint).int32(message.seatNumber);
        /* string status = 5; */
        if (message.status !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.status);
        /* string guest_users_id = 6; */
        if (message.guestUsersId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.guestUsersId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.Ticket
 */
export const Ticket = new Ticket$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClaimTicketRequest$Type extends MessageType<ClaimTicketRequest> {
    constructor() {
        super("svyne.purchase.ClaimTicketRequest", [
            { no: 1, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ClaimTicketRequest>): ClaimTicketRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.token = "";
        if (value !== undefined)
            reflectionMergePartial<ClaimTicketRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClaimTicketRequest): ClaimTicketRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string token */ 1:
                    message.token = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClaimTicketRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string token = 1; */
        if (message.token !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.token);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.ClaimTicketRequest
 */
export const ClaimTicketRequest = new ClaimTicketRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InviteTicketRequest$Type extends MessageType<InviteTicketRequest> {
    constructor() {
        super("svyne.purchase.InviteTicketRequest", [
            { no: 1, name: "purchase_tickets_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InviteTicketRequest>): InviteTicketRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.purchaseTicketsId = "";
        message.email = "";
        if (value !== undefined)
            reflectionMergePartial<InviteTicketRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InviteTicketRequest): InviteTicketRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string purchase_tickets_id */ 1:
                    message.purchaseTicketsId = reader.string();
                    break;
                case /* string email */ 2:
                    message.email = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InviteTicketRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string purchase_tickets_id = 1; */
        if (message.purchaseTicketsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.purchaseTicketsId);
        /* string email = 2; */
        if (message.email !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.email);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.InviteTicketRequest
 */
export const InviteTicketRequest = new InviteTicketRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListTicketsResponse$Type extends MessageType<ListTicketsResponse> {
    constructor() {
        super("svyne.purchase.ListTicketsResponse", [
            { no: 1, name: "tickets", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Ticket }
        ]);
    }
    create(value?: PartialMessage<ListTicketsResponse>): ListTicketsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tickets = [];
        if (value !== undefined)
            reflectionMergePartial<ListTicketsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListTicketsResponse): ListTicketsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.purchase.Ticket tickets */ 1:
                    message.tickets.push(Ticket.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListTicketsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.purchase.Ticket tickets = 1; */
        for (let i = 0; i < message.tickets.length; i++)
            Ticket.internalBinaryWrite(message.tickets[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.ListTicketsResponse
 */
export const ListTicketsResponse = new ListTicketsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScanRequest$Type extends MessageType<ScanRequest> {
    constructor() {
        super("svyne.purchase.ScanRequest", [
            { no: 1, name: "qr_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ScanRequest>): ScanRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.qrToken = "";
        message.eventsId = "";
        if (value !== undefined)
            reflectionMergePartial<ScanRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScanRequest): ScanRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string qr_token */ 1:
                    message.qrToken = reader.string();
                    break;
                case /* string events_id */ 2:
                    message.eventsId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScanRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string qr_token = 1; */
        if (message.qrToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.qrToken);
        /* string events_id = 2; */
        if (message.eventsId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventsId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.ScanRequest
 */
export const ScanRequest = new ScanRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScanResponse$Type extends MessageType<ScanResponse> {
    constructor() {
        super("svyne.purchase.ScanResponse", [
            { no: 1, name: "valid", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "holder_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ScanResponse>): ScanResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.valid = false;
        message.status = "";
        message.holderName = "";
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<ScanResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScanResponse): ScanResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool valid */ 1:
                    message.valid = reader.bool();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* string holder_name */ 3:
                    message.holderName = reader.string();
                    break;
                case /* string message */ 4:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScanResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool valid = 1; */
        if (message.valid !== false)
            writer.tag(1, WireType.Varint).bool(message.valid);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* string holder_name = 3; */
        if (message.holderName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.holderName);
        /* string message = 4; */
        if (message.message !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.ScanResponse
 */
export const ScanResponse = new ScanResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CheckInStats$Type extends MessageType<CheckInStats> {
    constructor() {
        super("svyne.purchase.CheckInStats", [
            { no: 1, name: "total", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "checked_in", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "remaining", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CheckInStats>): CheckInStats {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.total = 0;
        message.checkedIn = 0;
        message.remaining = 0;
        if (value !== undefined)
            reflectionMergePartial<CheckInStats>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CheckInStats): CheckInStats {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 total */ 1:
                    message.total = reader.int32();
                    break;
                case /* int32 checked_in */ 2:
                    message.checkedIn = reader.int32();
                    break;
                case /* int32 remaining */ 3:
                    message.remaining = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CheckInStats, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 total = 1; */
        if (message.total !== 0)
            writer.tag(1, WireType.Varint).int32(message.total);
        /* int32 checked_in = 2; */
        if (message.checkedIn !== 0)
            writer.tag(2, WireType.Varint).int32(message.checkedIn);
        /* int32 remaining = 3; */
        if (message.remaining !== 0)
            writer.tag(3, WireType.Varint).int32(message.remaining);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.purchase.CheckInStats
 */
export const CheckInStats = new CheckInStats$Type();
/**
 * @generated ServiceType for protobuf service svyne.purchase.PurchaseService
 */
export const PurchaseService = new ServiceType("svyne.purchase.PurchaseService", [
    { name: "CreatePurchase", options: {}, I: CreatePurchaseRequest, O: CreatePurchaseResponse },
    { name: "ReserveOpenCapacity", options: {}, I: ReserveOpenCapacityRequest, O: CreatePurchaseResponse },
    { name: "ConfirmPurchase", options: {}, I: ConfirmPurchaseRequest, O: AckResponse },
    { name: "CancelPurchase", options: {}, I: UuidValue, O: AckResponse },
    { name: "RefundPurchase", options: {}, I: UuidValue, O: AckResponse },
    { name: "GetPurchase", options: {}, I: UuidValue, O: Purchase },
    { name: "ListPurchases", options: {}, I: ListPurchasesRequest, O: ListPurchasesResponse },
    { name: "GetPurchaseStats", options: {}, I: UuidValue, O: PurchaseStats }
]);
/**
 * @generated ServiceType for protobuf service svyne.purchase.TicketService
 */
export const TicketService = new ServiceType("svyne.purchase.TicketService", [
    { name: "GetTicket", options: {}, I: UuidValue, O: Ticket },
    { name: "ClaimTicket", options: {}, I: ClaimTicketRequest, O: AckResponse },
    { name: "InviteTicket", options: {}, I: InviteTicketRequest, O: AckResponse },
    { name: "ListPurchaseTickets", options: {}, I: UuidValue, O: ListTicketsResponse }
]);
/**
 * @generated ServiceType for protobuf service svyne.purchase.CheckInService
 */
export const CheckInService = new ServiceType("svyne.purchase.CheckInService", [
    { name: "Scan", options: {}, I: ScanRequest, O: ScanResponse },
    { name: "GetCheckInStats", options: {}, I: UuidValue, O: CheckInStats }
]);
